name: gasop

on:
  push:
  workflow_dispatch:

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Run tests
        run: forge test --gas-report > gas-report.txt

      - name: Archive gas report
        uses: actions/upload-artifact@v4
        with:
          name: gas-report
          path: gas-report.txt
